### PR TITLE
New set of annotations as per YOLOv8 requirements 

### PR DESCRIPTION
**Pull request by samhubs**
Hi, 

I trained a Yolov8 based model on Loco and had to got through a number of steps for compiling the dataset in the required format, e.g. splitting the dataset into train and test, generating annotations, rearranging images inside an `image` directory. I would like to contribute the data here if that saves other's efforts and time. 

Quick question: I am hosting all the images on my GDrive, can you please push them to the hosting platform that you are using for the rest of the files?

Thanks,

### CODE REVIEW

**Comment by ShubhamUrmode** [comment]
hey sameer can you share weights file of yolo v8??

**Comment by samhubs** [comment]
@ShubhamUrmode - [Here](https://drive.google.com/file/d/1jtZ_PV3_HhoOkBPWx_96hBI4q3mth6pF/view?usp=share_link) are the weights and other inference files

**Comment by KoniHD** [comment]
Hi,
I came across this pull request and would be interested in the YOLOv8 labeling 😁  (not necessarily the drive link for downloads). Although this request has been open for over a year now I hope that it is still being considered?

**Comment by samhubs** [comment]
Sorry, it was a deprecated repo and shouldn't be live. I am deleting it for
now.

**Pull request closed without merging**
